import subprocess
import os
import re
import time
from datetime import datetime
from llm_providers import LLMConfig, LLMProviderFactory

class LLMCompiler:
    def __init__(self, log_callback):
        self.log = log_callback
        self.tectonic_path = os.path.join("engines", "tectonic.exe")
        
        # LLM Configuration - will be set via set_llm_config
        self.llm_config: LLMConfig = None
        self.provider = None
        
        # Legacy fields for backward compatibility
        self.engine = "ollama" 
        self.api_key = ""
        self.active_model = "llama3.2" 
        self.enable_web_search = False 
        
        self.context_length = 4096 
        self.keep_alive = "10m"
        self.temperature = 0.2
        self.pages = "Any"
        self.graphics_level = 0.5
        self.active_elements = []
        self.custom_header = ""
        self.custom_watermark = ""

    def set_llm_config(self, llm_config: LLMConfig):
        """Set the LLM configuration and create provider instance"""
        self.llm_config = llm_config
        self.provider = LLMProviderFactory.create(llm_config, self.log)
        
        # Update legacy fields for backward compatibility
        self.engine = llm_config.provider
        self.api_key = llm_config.api_key
        self.active_model = llm_config.model
        self.context_length = llm_config.context_length
        self.keep_alive = llm_config.keep_alive
        self.temperature = llm_config.temperature

    def _get_god_mode_preamble(self, mode="meeting"):
        title_text = self.custom_header if self.custom_header else ("Meeting Summary" if mode == "meeting" else "Class / Lecture Notes")
        preamble = [
            "\\documentclass{article}", "\\usepackage{fontspec}", "\\usepackage[margin=1in]{geometry}",
            "\\usepackage{amsmath, amssymb}", "\\usepackage{xcolor}", "\\usepackage[most]{tcolorbox}", 
            "\\usepackage{tikz}", "\\usepackage{pgfplots}", "\\pgfplotsset{compat=1.18}",
            "\\usepackage{listings}", "\\usepackage{booktabs}", "\\usepackage{colortbl}",
            "\\usepackage{algorithm}", "\\usepackage{algpseudocode}", "\\usepackage{hyperref}",
            f"\\title{{{title_text}}}", "\\author{Generated by Kurt}", "\\date{\\today}"
        ]

        if "Header & Footer" in self.active_elements:
            preamble.append("\\usepackage{fancyhdr}\n\\pagestyle{fancy}\n\\fancyhf{}")
            preamble.append(f"\\fancyhead[C]{{{title_text}}}") 
            preamble.append("\\fancyfoot[C]{\\thepage}")

        if "Draft Watermark" in self.active_elements:
            preamble.append("\\usepackage{draftwatermark}")
            wm_text = self.custom_watermark if self.custom_watermark else "DRAFT"
            preamble.append(f"\\SetWatermarkText{{{wm_text}}}")
            preamble.append("\\SetWatermarkLightness{0.9}")

        return "\n".join(preamble)

    def generate_document(self, transcript, context, mode="meeting"):
        system_prompt = (
            "You are an expert academic and corporate analyst. Your ONLY job is to synthesize data into LaTeX documents. "
            "Generate the BODY of a LaTeX document only. Start immediately with \\begin{document} and end with \\end{document}. "
            "CRITICAL RULES: "
            "1. NEVER output raw transcripts. You must analyze and summarize. "
            "2. NEVER use the phrase 'Meeting Transcript' as a header. "
            "3. Format beautifully using \\section*{}, \\textbf{}, and \\begin{itemize}. "
            "4. Escape LaTeX special characters. 5. ABSOLUTELY NO PLACEHOLDERS."
        )

        if self.pages.lower() != "any" and self.pages.strip() != "":
            system_prompt += f"\nTARGET LENGTH: Ensure the document is highly detailed, approximately {self.pages} pages long."

        if self.active_elements:
            system_prompt += f"\nSTYLING RULES: Include the following LaTeX body elements: {', '.join(self.active_elements)}."

        user_prompt = f"--- SUPPORTING MATERIALS ---\n{context}\n\n--- RAW DATA TO ANALYZE ---\n{transcript}\n\n"
        user_prompt += "--- FINAL STRICT INSTRUCTIONS ---\nDO NOT copy or regurgitate the raw data above. Synthesize it. NEVER use placeholder comments. "
        
        if mode == "class":
            user_prompt += "You are writing EXPANSIVE ACADEMIC CLASS NOTES. ELABORATE deeply using your knowledge. You MUST strictly use these exact headers: \n\\section*{Core Concepts Explained} \n\\section*{Important Definitions \\& Formulas} \n\\section*{Study Guide / Key Takeaways} "
        else:
            user_prompt += "You are writing a CORPORATE MEETING SUMMARY. You MUST strictly use these exact headers: \n\\section*{Executive Summary} \n\\section*{Key Discussion Points} \n\\section*{Action Items} (Must be a table). "

        # Use new provider system if configured, fallback to legacy
        if self.provider and self.llm_config:
            provider_name = self.llm_config.provider
            model_name = self.llm_config.model
        else:
            provider_name = self.engine
            model_name = self.active_model
            
        self.log(f"[*] Querying {provider_name.upper()} ({model_name}) in {mode.upper()} mode...")
        
        try:
            full_text = ""
            tps_string = "Speed: N/A"
            start_time = time.time()

            if self.provider:
                # Use new unified provider system
                messages = [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ]
                
                # Configure generation parameters
                kwargs = {
                    "temperature": float(self.temperature),
                    "enable_search": self.enable_web_search and provider_name.lower() == "gemini"
                }
                
                # Provider-specific parameters
                if provider_name.lower() == "ollama":
                    kwargs["num_ctx"] = self.context_length
                    kwargs["keep_alive"] = self.keep_alive
                elif provider_name.lower() in ["openai", "anthropic", "custom"]:
                    kwargs["max_tokens"] = self.llm_config.max_tokens if self.llm_config else 8192
                
                full_text = self.provider.generate(messages, **kwargs)
                
                elapsed = time.time() - start_time
                # Try to get token info from last response
                if hasattr(self.provider, '_last_response') and self.provider._last_response:
                    resp = self.provider._last_response
                    if hasattr(resp, 'tokens_used') and resp.tokens_used and elapsed > 0:
                        tps = resp.tokens_used / elapsed
                        tps_string = f"Speed: {tps:.1f} t/s ({'API' if provider_name != 'ollama' else 'Local GPU'})"

            elif provider_name == "gemini":
                # Legacy Gemini support
                from google import genai
                from google.genai import types
                client = genai.Client(api_key=self.api_key)
                
                config_dict = {
                    "system_instruction": system_prompt,
                    "temperature": float(self.temperature)
                }
                
                # THE GATEKEEPER
                model_lower = self.active_model.lower()
                is_eligible_flash = "flash" in model_lower and "gemini-3" not in model_lower
                
                if self.enable_web_search and is_eligible_flash:
                    config_dict["tools"] = [{'google_search': {}}]
                    self.log("[+] Summarizer utilizing Live Google Search.")
                
                response = client.models.generate_content(
                    model=self.active_model,
                    contents=user_prompt,
                    config=types.GenerateContentConfig(**config_dict)
                )
                full_text = response.text
                duration = time.time() - start_time
                if response.usage_metadata and duration > 0:
                    tps = response.usage_metadata.candidates_token_count / duration
                    tps_string = f"Speed: {tps:.1f} t/s (API)"

            else:
                # Legacy Ollama support
                import ollama
                response = ollama.chat(
                    model=self.active_model, 
                    messages=[{'role': 'system', 'content': system_prompt}, {'role': 'user', 'content': user_prompt}],
                    options={"num_ctx": self.context_length, "temperature": float(self.temperature)},
                    keep_alive=self.keep_alive 
                )
                full_text = response['message']['content']
                if 'eval_count' in response and 'eval_duration' in response:
                    seconds = response['eval_duration'] / 1e9
                    if seconds > 0:
                        tps = response['eval_count'] / seconds
                        tps_string = f"Speed: {tps:.1f} t/s (Local GPU)"

            full_text = re.sub(r"```latex\n?", "", full_text, flags=re.IGNORECASE)
            full_text = re.sub(r"```\n?", "", full_text)
            match = re.search(r"\\begin\{document\}(.*?)\\end\{document\}", full_text, re.DOTALL | re.IGNORECASE)
            body_content = match.group(1).strip() if match else full_text.strip()
            body_content = re.sub(r"\\usepackage(\[.*?\])?\{.*?\}", "", body_content, flags=re.IGNORECASE)
            body_content = re.sub(r"\\documentclass(\[.*?\])?\{.*?\}", "", body_content, flags=re.IGNORECASE)
            body_content = re.sub(r"\\begin\{document\}", "", body_content, flags=re.IGNORECASE)
            body_content = re.sub(r"\\end\{document\}", "", body_content, flags=re.IGNORECASE)

            now = datetime.now().strftime("%B %d, %Y at %I:%M %p")
            time_block = f"\n\\vfill\n\\begin{{center}}\n\\footnotesize \\textit{{Generated by Kurt on {now}}}\n\\end{{center}}\n"
            latex_code = f"{self._get_god_mode_preamble(mode)}\n\\begin{{document}}\n\\maketitle\n{body_content}\n{time_block}\n\\end{{document}}"
            return latex_code, tps_string
            
        except Exception as e:
            self.log(f"[-] Compiler Error: {e}")
            raise e

    def compile_to_pdf(self, latex_content, output_name="Document"):
        safe_name = re.sub(r'[^A-Za-z0-9_\-]', '_', output_name)
        base_dir = os.path.abspath(os.getcwd())
        exports_dir = os.path.join(base_dir, "exports")
        os.makedirs(exports_dir, exist_ok=True)
        tex_file = os.path.join(exports_dir, f"{safe_name}.tex")
        tectonic_exe = os.path.join(base_dir, "engines", "tectonic.exe")
        with open(tex_file, "w", encoding="utf-8") as f: f.write(latex_content)
        self.log(f"[*] Compiling PDF via Tectonic...")
        try:
            result = subprocess.run([tectonic_exe, tex_file], capture_output=True, text=True)
            if result.returncode == 0: return os.path.join(exports_dir, f"{safe_name}.pdf") 
            else:
                self.log(f"[-] Tectonic Compilation Failed.")
                with open(os.path.join(exports_dir, f"{safe_name}_ERROR_LOG.txt"), "w", encoding="utf-8") as ef: ef.write(result.stderr)
                return None
        except Exception as e:
            self.log(f"[-] Compilation Engine Error: {e}")
            return None