import ollama
import subprocess
import os
import re
from datetime import datetime

class LLMCompiler:
    def __init__(self, log_callback, model_name="llama3.2"):
        self.model_name = model_name
        self.tectonic_path = os.path.join("engines", "tectonic.exe")
        self.log = log_callback
        
        # Advanced Settings State
        self.context_length = 4096 
        self.keep_alive = "10m"
        self.temperature = 0.2
        self.pages = "Any"
        self.graphics_level = 0.5
        self.active_elements = []
        
        # Custom Element Text
        self.custom_header = ""
        self.custom_watermark = ""

    def _get_dynamic_preamble(self):
        """Dynamically builds the preamble based on UI checkboxes, guaranteeing no crashes."""
        # Fallback to "Meeting Summary" if user didn't type a custom header
        title_text = self.custom_header if self.custom_header else "Meeting Summary"
        
        preamble = [
            "\\documentclass{article}",
            "\\usepackage{fontspec}",
            "\\usepackage[margin=1in]{geometry}",
            "\\usepackage{amsmath, amssymb}",
            "\\usepackage{xcolor}",
            "\\usepackage{tcolorbox}",
            "\\usepackage{tikz}",
            "\\usepackage{pgfplots}",
            "\\pgfplotsset{compat=1.18}",
            "\\usepackage{listings}",
            "\\usepackage{booktabs}",
            "\\usepackage{colortbl}",
            "\\usepackage{algorithm}",
            "\\usepackage{algpseudocode}",
            "\\usepackage{hyperref}",
            
            # --- CRITICAL FIX: ALWAYS DEFINE TITLE DATA ---
            # This ensures \maketitle will NEVER crash the compiler again.
            f"\\title{{{title_text}}}",
            "\\author{Generated by AI Meeting Pro}",
            "\\date{\\today}"
        ]

        # --- DYNAMIC INJECTIONS ---
        if "Header & Footer (fancyhdr)" in self.active_elements:
            preamble.append("\\usepackage{fancyhdr}")
            preamble.append("\\pagestyle{fancy}")
            preamble.append("\\fancyhf{}")
            preamble.append(f"\\fancyhead[C]{{{title_text}}}") # Uses your custom text
            preamble.append("\\fancyfoot[C]{\\thepage}")

        if "Draft Watermark" in self.active_elements:
            preamble.append("\\usepackage{draftwatermark}")
            wm_text = self.custom_watermark if self.custom_watermark else "DRAFT"
            preamble.append(f"\\SetWatermarkText{{{wm_text}}}")
            preamble.append("\\SetWatermarkLightness{0.9}")

        return "\n".join(preamble)

    def generate_summary(self, transcript, context):
        """Sends data to Ollama and surgically extracts ONLY the document body."""
        
        system_prompt = (
            "You are an expert LaTeX content generator. Generate the BODY of a LaTeX document. "
            "DO NOT write a preamble. DO NOT use \\documentclass or \\usepackage. "
            "Start your response immediately with \\begin{document} and end with \\end{document}. "
            "1. Escape LaTeX special characters (e.g., \\$, \\%, \\&, \\_). "
            "2. If making a checklist, use the \\square command. "
        )

        if self.pages.lower() != "any" and self.pages.strip() != "":
            system_prompt += f"\nTARGET LENGTH: Make the document approx {self.pages} pages long."

        if self.graphics_level < 0.2:
            system_prompt += "\nGRAPHICS: Purely text. Do NOT use any tables, charts, or figures."
        elif self.graphics_level > 0.8:
            system_prompt += "\nGRAPHICS: Highly visual. Maximize use of tables and TikZ charts."
        else:
            system_prompt += "\nGRAPHICS: Balanced. Use standard tables for action items."

        if self.active_elements:
            elements_str = ", ".join(self.active_elements)
            # Only tell the LLM about elements it needs to draw in the body.
            system_prompt += f"\nSTYLING RULES: Include the following LaTeX body elements: {elements_str}."

        user_prompt = f"Supporting Materials:\n{context}\n\nMeeting Transcript:\n{transcript}"
        
        self.log(f"[*] Querying {self.model_name} (Temp: {self.temperature:.2f}, Keep-Alive: {self.keep_alive})...")
        
        try:
            response = ollama.chat(
                model=self.model_name,
                messages=[
                    {'role': 'system', 'content': system_prompt},
                    {'role': 'user', 'content': user_prompt},
                ],
                options={"num_ctx": self.context_length, "temperature": float(self.temperature)},
                keep_alive=self.keep_alive 
            )
            
            full_text = response['message']['content']
            
            # 1. Clean out markdown ticks
            full_text = re.sub(r"```latex\n?", "", full_text, flags=re.IGNORECASE)
            full_text = re.sub(r"```\n?", "", full_text)
            
            # 2. SURGICAL EXTRACTION: Grab ONLY what is inside the document tags
            match = re.search(r"\\begin\{document\}(.*?)\\end\{document\}", full_text, re.DOTALL | re.IGNORECASE)
            
            if match:
                body_content = match.group(1).strip()
                self.log("[+] Document body successfully extracted.")
            else:
                self.log("[-] Warning: Missing document tags. Cleaning raw text...")
                body_content = full_text.strip()
                
            # 3. NUKE ROGUE PACKAGES: Delete any packages/headers the LLM hallucinated
            body_content = re.sub(r"\\usepackage(\[.*?\])?\{.*?\}", "", body_content, flags=re.IGNORECASE)
            body_content = re.sub(r"\\documentclass(\[.*?\])?\{.*?\}", "", body_content, flags=re.IGNORECASE)
            body_content = re.sub(r"\\begin\{document\}", "", body_content, flags=re.IGNORECASE)
            body_content = re.sub(r"\\end\{document\}", "", body_content, flags=re.IGNORECASE)

            # 4. TIMESTAMP INJECTION
            now = datetime.now().strftime("%B %d, %Y at %I:%M %p")
            time_block = f"\n\\vfill\n\\begin{{center}}\n\\footnotesize \\textit{{Generated by AI Meeting Pro on {now}}}\n\\end{{center}}\n"

            # 5. ASSEMBLE PERFECT DOCUMENT
            latex_code = (
                f"{self._get_dynamic_preamble()}\n"
                "\\begin{document}\n"
                f"{body_content}\n"
                f"{time_block}\n"
                "\\end{document}"
            )

            return latex_code
            
        except Exception as e:
            self.log(f"[-] Ollama Error: {e}")
            raise e

    def compile_to_pdf(self, latex_content, output_name="Meeting_Summary"):
        """Compiles LaTeX string into a PDF with sanitized paths."""
        safe_name = re.sub(r'[^A-Za-z0-9_\-]', '_', output_name)
        
        base_dir = os.path.abspath(os.getcwd())
        exports_dir = os.path.join(base_dir, "exports")
        os.makedirs(exports_dir, exist_ok=True)
        
        tex_file = os.path.join(exports_dir, f"{safe_name}.tex")
        tectonic_exe = os.path.join(base_dir, "engines", "tectonic.exe")
        
        # Enforce strict UTF-8 writing to prevent encoding crashes
        with open(tex_file, "w", encoding="utf-8") as f:
            f.write(latex_content)
        
        self.log(f"[*] Compiling PDF via Tectonic ({safe_name}.pdf)...")
        try:
            result = subprocess.run([tectonic_exe, tex_file], capture_output=True, text=True)
            if result.returncode == 0:
                return os.path.join(exports_dir, f"{safe_name}.pdf") 
            else:
                self.log(f"[-] Tectonic Compilation Failed. Check Error Log.")
                
                # Save the exact error to a text file for debugging
                error_log = os.path.join(exports_dir, f"{safe_name}_ERROR_LOG.txt")
                with open(error_log, "w", encoding="utf-8") as ef:
                    ef.write(result.stderr)
                    
                return None
        except Exception as e:
            self.log(f"[-] Compilation Engine Error: {e}")
            return None